const numrs = require('../index.js'); // Assuming index.js handles loading the .node file
// Or if direct:
// const numrs = require('../index.node');

// However, typically index.js is generated by napi-cli or wrapper.
// Checking file listing earlier, index.js exists (1734 bytes).

async function run() {
    console.log("NumRs Autograd Demo");

    // 1. Create Tensors
    // x = [1.0, 2.0, 3.0]
    const xData = new Float32Array([1.0, 2.0, 3.0]);
    const x = new numrs.JsTensor(xData, [3], true); // requires_grad = true

    // y = [2.0, 3.0, 4.0]
    const yData = new Float32Array([2.0, 3.0, 4.0]);
    const y = new numrs.JsTensor(yData, [3], true);

    console.log(`x: ${x.toString()}`);
    console.log(`y: ${y.toString()}`);

    // 2. Perform operations
    // z = x * y + x
    // expected z = [1*2+1, 2*3+2, 3*4+3] = [3, 8, 15]

    const prod = x.mul(y);
    const z = prod.add(x);

    console.log(`z = x * y + x: ${z.toString()}`);

    // 3. Backward
    // dL/dz = 1 (implicitly)
    // z = x*y + x
    // dz/dx = y + 1 => [2+1, 3+1, 4+1] = [3, 4, 5]
    // dz/dy = x => [1, 2, 3]

    z.backward();

    console.log("Backward pass complete.");

    // 4. Check gradients
    const xGrad = x.grad;
    const yGrad = y.grad;

    if (xGrad) {
        console.log(`x.grad: ${xGrad.toString()}`);
        // Verify values
        // [3.0, 4.0, 5.0]
    } else {
        console.log("x.grad is missing!");
    }

    if (yGrad) {
        console.log(`y.grad: ${yGrad.toString()}`);
        // Verify values
        // [1.0, 2.0, 3.0]
    } else {
        console.log("y.grad is missing!");
    }

    // 5. More complex: Reduction
    // L = sum(z)
    // L = sum(x*y + x)
    // dL/dx = y + 1 (broadcasted if needed, but here elementwise)

    x.zeroGrad();
    y.zeroGrad();

    const z2 = x.mul(y).add(x);
    const L = z2.sum();

    console.log(`L = sum(z): ${L.toString()}`);

    L.backward();

    const xGrad2 = x.grad;
    console.log(`x.grad (after sum): ${xGrad2 ? xGrad2.toString() : 'null'}`);
}

run().catch(console.error);
